export type Reward = {
  title: string;
  amount: number;
  description: string;
  backers?: number;
};

export type FaqItem = {
  question: string;
  answer: string;
};

export type Startup = {
  id: string;
  title: string;
  tagline: string;
  description: string;
  longDescription?: string;
  category: string;
  creator: string;
  creatorBio?: string;
  creatorAvatar?: string;
  image: string;
  goal: number;
  raised: number;
  backers: number;
  daysLeft: number;
  location?: string;
  featured?: boolean;
  risksAndChallenges?: string;
  faq?: FaqItem[];
  rewards?: Reward[];
};

export const startups: Startup[] = [
  {
    id: "solar-charger",
    title: "SunFlow — Portable Solar Charger",
    tagline: "Charge anywhere. Never run out of power.",
    description: "SunFlow is a compact, foldable solar panel that fits in your backpack.",
    longDescription: "SunFlow is a compact, foldable solar panel that fits in your backpack. With 25W output and USB-C PD, it charges phones, tablets, and even laptops. Perfect for hikers, digital nomads, and anyone who values freedom from power outlets.\n\nWe've spent 18 months on R&D with a focus on durability and efficiency. The panels are rated IP65 and the hinge mechanism has been tested for 10,000+ folds. Our manufacturing partner in Taiwan is ready for production — we just need your support to cover the first batch and tooling.",
    category: "Tech & Gadgets",
    creator: "EcoTech Labs",
    creatorBio: "EcoTech Labs is a small team in Amsterdam focused on sustainable consumer electronics. We've shipped two previous campaigns and believe in transparent, ethical production.",
    image: "https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=800&q=80",
    goal: 50000,
    raised: 34200,
    backers: 412,
    daysLeft: 18,
    location: "Amsterdam, NL",
    risksAndChallenges: "Component supply is secured for the first run. Any delays would be due to customs or logistics; we've built in a 4-week buffer. We'll communicate openly via updates if anything shifts.",
    faq: [
      { question: "What's the warranty?", answer: "2 years on the panel and 1 year on the electronics. We'll provide a clear warranty card in the box." },
      { question: "Can it charge a laptop?", answer: "Yes — with USB-C PD it can charge most ultrabooks and MacBooks, though full charge will take longer than a wall adapter." },
      { question: "When do you ship?", answer: "We aim to ship rewards by August 2025. Backers will get tracking and updates." },
    ],
    rewards: [
      { title: "Early Bird", amount: 49, description: "One SunFlow unit. Save €20 off retail.", backers: 120 },
      { title: "SunFlow", amount: 69, description: "One SunFlow portable solar charger. All colors.", backers: 280 },
      { title: "SunFlow + Cable Kit", amount: 89, description: "SunFlow plus our USB-C and Lightning cable set.", backers: 12 },
    ],
  },
  {
    id: "urban-garden-kit",
    title: "GrowBox — Urban Garden Kit",
    tagline: "Fresh herbs and veggies from your windowsill.",
    description: "GrowBox is an all-in-one hydroponic kit for growing herbs and small vegetables indoors.",
    longDescription: "GrowBox is an all-in-one hydroponic kit for growing herbs and small vegetables indoors. No soil, no mess — just add water and our nutrient pods. Smart LED lighting and an app remind you when to harvest.\n\nWe want to make growing your own food accessible to every city dweller. The kit includes the unit, seeds for 3 herb varieties, and a 6-month supply of nutrients. The app works with iOS and Android and lets you track growth and get tips.",
    category: "Lifestyle",
    creator: "Green Roots",
    creatorBio: "Green Roots is a Berlin-based startup. We've run pop-up workshops in 5 cities and have a growing community of urban growers.",
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80",
    goal: 25000,
    raised: 28900,
    backers: 623,
    daysLeft: 5,
    location: "Berlin, DE",
    risksAndChallenges: "We've already produced a small pilot batch. Main risk is demand exceeding our first run — we'll open a pre-order list and fulfill in waves if needed.",
    faq: [
      { question: "How much power does it use?", answer: "About 8W on average — similar to a small LED lamp. Timer and app help keep usage efficient." },
      { question: "Which herbs can I grow?", answer: "Basil, mint, parsley, cilantro, and our 'salad mix' for small leaves. We'll add more seed options post-campaign." },
    ],
    rewards: [
      { title: "GrowBox Standard", amount: 79, description: "One GrowBox unit + seeds + 6 months nutrients.", backers: 450 },
      { title: "GrowBox Duo", amount: 139, description: "Two units. Perfect for kitchen + living room.", backers: 173 },
    ],
  },
  {
    id: "community-bike-share",
    title: "WijkFiets — Neighborhood Bike Share",
    tagline: "Borrow a bike. Share the ride. Clean the air.",
    description: "WijkFiets is a community-owned bike share for neighborhoods without commercial schemes.",
    longDescription: "WijkFiets is a community-owned bike share for neighborhoods without commercial schemes. Members get a key to local hubs; bikes are maintained by volunteers and funded by small monthly fees.\n\nWe're piloting in three districts and need funds for 50 more bikes and 10 new hubs. Each hub has 5–8 bikes, a simple lock system, and a repair kit. Membership is €5/month and includes insurance. We work with local councils and housing associations to place hubs.",
    category: "Community",
    creator: "Stichting WijkFiets",
    creatorBio: "Stichting WijkFiets is a nonprofit in Rotterdam. We're cyclists, parents, and neighbors who want affordable, local mobility.",
    image: "https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=800&q=80",
    goal: 35000,
    raised: 18200,
    backers: 198,
    daysLeft: 42,
    location: "Rotterdam, NL",
    risksAndChallenges: "Weather and vandalism can affect bikes. We'll have a maintenance schedule and spare parts. If a hub underperforms, we'll relocate with community input.",
    faq: [
      { question: "How do I become a member?", answer: "After the campaign we'll open sign-up. You'll get a key and app access. First month is free for backers." },
      { question: "Where will the new hubs be?", answer: "We're in talks with two districts. Backers will get a say via a short survey once we're funded." },
    ],
    rewards: [
      { title: "Supporter", amount: 15, description: "Thanks on our site + 3 months free membership.", backers: 89 },
      { title: "Member + Key", amount: 60, description: "1 year membership + key. Early backer price.", backers: 109 },
    ],
  },
  {
    id: "indie-board-game",
    featured: true,
    title: "Realm of Shadows — Board Game",
    tagline: "A cooperative strategy game for 2–5 players.",
    description: "Realm of Shadows is a fully illustrated board game where players work together to save a kingdom.",
    longDescription: "Realm of Shadows is a cooperative strategy board game for 2–5 players. You work together to save a kingdom from an ancient curse. 80+ cards, miniatures, and a modular board.\n\nDesigned by tabletop veterans and illustrated by award-winning artists. Playtime is 60–90 minutes. Production is lined up with a manufacturer in Poland — we need your support to print the first run and ship to backers worldwide.",
    category: "Games",
    creator: "Dice & Lore Studio",
    creatorBio: "We're a small studio in Utrecht. We've released two print-and-play games; this is our first full physical release.",
    image: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800&q=80",
    goal: 40000,
    raised: 52100,
    backers: 890,
    daysLeft: 12,
    location: "Utrecht, NL",
    risksAndChallenges: "Shipping and customs can cause delays. We're using EU and US fulfillment centers to reduce issues. If anything slips we'll update backers every two weeks.",
    faq: [
      { question: "Is it language-dependent?", answer: "The rulebook will be in English. Card text is minimal; we'll provide language packs (DE, NL, FR) as add-ons." },
      { question: "Solo mode?", answer: "Yes — official solo rules are included. You control two characters." },
    ],
    rewards: [
      { title: "Pledge", amount: 45, description: "Base game. All stretch goals included.", backers: 520 },
      { title: "Deluxe", amount: 75, description: "Game + premium box + art book.", backers: 310 },
      { title: "Retailer", amount: 180, description: "6 copies for retail. Inquire for more.", backers: 60 },
    ],
  },
  {
    id: "refill-app",
    title: "Refill — Find Refill Stations Near You",
    tagline: "Less plastic. More refill.",
    description: "Refill is an app that maps refill stations for water, detergent, coffee, and dry goods.",
    longDescription: "Refill is an app that maps refill stations for water, detergent, coffee, and dry goods. Users avoid single-use packaging; shops get more foot traffic.\n\nWe're live in 12 cities and want to expand across the Benelux and add features like loyalty rewards and business dashboards. This campaign funds the next year of development and community outreach.",
    category: "Environment",
    creator: "Zero Waste Digital",
    creatorBio: "Zero Waste Digital is a small team in Brussels. We built Refill as a side project and it's grown into a community of 15k+ users.",
    image: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=800&q=80",
    goal: 20000,
    raised: 12400,
    backers: 356,
    daysLeft: 28,
    location: "Brussels, BE",
    risksAndChallenges: "We depend on partners and volunteers to keep data accurate. We'll invest in moderation and verification tools.",
    faq: [
      { question: "Is the app free?", answer: "Yes for users. Businesses can list for free; we'll offer premium listing later." },
      { question: "Which cities next?", answer: "Antwerp, Cologne, and Lille are next. Backers can vote for one more city." },
    ],
    rewards: [
      { title: "Thanks", amount: 5, description: "Your name in the app and our thanks.", backers: 200 },
      { title: "Pro for 1 year", amount: 25, description: "Pro features: offline maps, no ads, early access.", backers: 156 },
    ],
  },
  {
    id: "kids-coding-kit",
    title: "CodeBuddy — Learn to Code, Ages 6+",
    tagline: "Coding through stories and play.",
    description: "CodeBuddy is a subscription box that teaches kids programming with story-based challenges.",
    longDescription: "CodeBuddy is a subscription box that teaches kids programming with story-based challenges and a friendly robot character. Each month: a new adventure, physical components, and an app that runs on tablet or phone.\n\nNo screen-time guilt — it's creative, logical, and fun. Backed by educators and tested in 20 schools. The first box introduces sequences and loops; later boxes cover conditionals, variables, and simple projects.",
    category: "Education",
    creator: "LearnPlay Labs",
    creatorBio: "LearnPlay Labs is based in Munich. We're parents and educators who want coding to be as accessible as reading.",
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&q=80",
    goal: 30000,
    raised: 41000,
    backers: 720,
    daysLeft: 3,
    location: "Munich, DE",
    risksAndChallenges: "Subscription fulfillment is complex. We've partnered with a fulfillment center and will ship in monthly batches. First box ships in September.",
    faq: [
      { question: "What age exactly?", answer: "Ages 6–10 is the sweet spot. Older kids can go faster; we have 'challenge mode' for them." },
      { question: "Can schools order?", answer: "Yes — we have a school pack (10 boxes) and classroom guide. Contact us for a quote." },
    ],
    rewards: [
      { title: "1-month trial", amount: 29, description: "First box only. Perfect to try.", backers: 180 },
      { title: "6-month subscription", amount: 149, description: "6 monthly boxes. Save 15%.", backers: 410 },
      { title: "12-month subscription", amount: 249, description: "12 monthly boxes. Save 25%.", backers: 130 },
    ],
  },
  {
    id: "smart-watch-eco",
    title: "Terra Watch — Eco Smartwatch",
    tagline: "Sustainable tech on your wrist.",
    description: "A smartwatch made from recycled ocean plastic and conflict-free minerals. Full health tracking and 2-week battery.",
    category: "Tech & Gadgets",
    creator: "OceanTech",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80",
    goal: 75000,
    raised: 42100,
    backers: 534,
    daysLeft: 24,
    location: "Hamburg, DE",
  },
  {
    id: "noise-cancelling-buds",
    title: "QuietLoop — True Wireless Earbuds",
    tagline: "Silence the world. Hear what matters.",
    description: "Premium noise-cancelling earbuds with 30h battery and transparency mode. Designed for commuters and focus.",
    category: "Tech & Gadgets",
    creator: "SoundForge",
    image: "https://images.unsplash.com/photo-1598331668826-20cecc596b86?w=800&q=80",
    goal: 30000,
    raised: 67800,
    backers: 1202,
    daysLeft: 8,
    location: "London, UK",
  },
  {
    id: "indie-rpg-game",
    title: "Chronicles of the Lost Realm — RPG",
    tagline: "A narrative-driven RPG for PC and console.",
    description: "Single-player fantasy RPG with branching story, hand-painted art, and 40+ hours of gameplay. From a team of industry veterans.",
    category: "Games",
    creator: "Mythic Games",
    image: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=800&q=80",
    goal: 120000,
    raised: 89000,
    backers: 2103,
    daysLeft: 19,
    location: "Stockholm, SE",
  },
  {
    id: "card-game-family",
    title: "Wild Deal — Family Card Game",
    tagline: "Bluff, trade, and win. For ages 8+.",
    description: "A fast-paced card game for 3–6 players. Beautiful illustrations and easy to learn, hard to master.",
    category: "Games",
    creator: "TableTop Co",
    image: "https://images.unsplash.com/photo-1611195974226-a84931c0d9d6?w=800&q=80",
    goal: 15000,
    raised: 22100,
    backers: 445,
    daysLeft: 2,
    location: "Lyon, FR",
  },
  {
    id: "art-book-illustration",
    title: "Visions — Art Book & Print Set",
    tagline: "A curated collection of digital art from 20 artists.",
    description: "Hardcover art book (120 pages) plus optional print set. Celebrating nature and fantasy from illustrators around the world.",
    category: "Art",
    creator: "Collective Vision",
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&q=80",
    goal: 18000,
    raised: 24500,
    backers: 612,
    daysLeft: 14,
    location: "Porto, PT",
  },
  {
    id: "documentary-film",
    title: "The Last Forest — Documentary",
    tagline: "One year inside Europe's last old-growth forest.",
    description: "Feature-length documentary following researchers and activists in the Białowieża Forest. Cinematic 4K, release in 2026.",
    category: "Film & Video",
    creator: "Earth Frame Films",
    image: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&q=80",
    goal: 55000,
    raised: 38200,
    backers: 892,
    daysLeft: 31,
    location: "Warsaw, PL",
  },
  {
    id: "modular-synth",
    title: "PulseBox — Modular Synth Kit",
    tagline: "Build your own analog synthesizer.",
    description: "DIY kit with 12 modules, patch cables, and a step-by-step guide. No soldering required. From beginners to pros.",
    category: "Music",
    creator: "SynthLab",
    image: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&q=80",
    goal: 40000,
    raised: 52100,
    backers: 678,
    daysLeft: 6,
    location: "Vienna, AT",
  },
  {
    id: "minimal-wallet",
    title: "SlimFold — Minimalist Wallet",
    tagline: "Cards and cash. Nothing more.",
    description: "Ultra-thin wallet made from recycled materials. Holds 8 cards and notes. Fits in any pocket.",
    category: "Design",
    creator: "Everyday Carry Co",
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&q=80",
    goal: 8000,
    raised: 15600,
    backers: 423,
    daysLeft: 11,
    location: "Copenhagen, DK",
  },
  {
    id: "children-book",
    title: "Luna & the Night Garden — Children's Book",
    tagline: "A bedtime story about curiosity and kindness.",
    description: "Illustrated picture book for ages 3–7. Luna discovers a magical garden at night. Hardcover, 32 pages.",
    category: "Publishing",
    creator: "Moonlit Stories",
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&q=80",
    goal: 12000,
    raised: 18900,
    backers: 534,
    daysLeft: 9,
    location: "Edinburgh, UK",
  },
  // More Tech & Gadgets
  {
    id: "keyboard-mechanical",
    title: "ClackFlow — Mechanical Keyboard Kit",
    tagline: "Build your dream keyboard. Hot-swap, RGB, wireless.",
    description: "Premium mechanical keyboard kit with hot-swap sockets, per-key RGB, and Bluetooth. Available in 65% and TKL.",
    category: "Tech & Gadgets",
    creator: "KeyLabs",
    image: "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=800&q=80",
    goal: 35000,
    raised: 48200,
    backers: 756,
    daysLeft: 15,
    location: "Taipei, TW",
  },
  {
    id: "webcam-4k",
    title: "StreamPro — 4K Webcam for Creators",
    tagline: "Broadcast-grade quality for your desk.",
    description: "4K 60fps webcam with built-in ring light and noise-cancelling mic. Perfect for streamers and remote workers.",
    category: "Tech & Gadgets",
    creator: "StreamGear",
    image: "https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=800&q=80",
    goal: 45000,
    raised: 31200,
    backers: 423,
    daysLeft: 22,
    location: "Shenzhen, CN",
  },
  {
    id: "power-bank-100w",
    title: "MegaCharge — 100W Power Bank",
    tagline: "Charge laptop + phone. One brick.",
    description: "20000mAh power bank with 100W USB-C PD. Charges MacBook, phones, and tablets. TSA-friendly.",
    category: "Tech & Gadgets",
    creator: "PowerUp",
    image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=800&q=80",
    goal: 28000,
    raised: 18900,
    backers: 312,
    daysLeft: 35,
    location: "Munich, DE",
  },
  // More Lifestyle
  {
    id: "meditation-cushion",
    title: "ZenSeat — Ergonomic Meditation Cushion",
    tagline: "Sit longer. Sit better.",
    description: "Ergonomic meditation cushion with memory foam and washable cover. For floor sitting and mindfulness.",
    category: "Lifestyle",
    creator: "Calm Craft",
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80",
    goal: 15000,
    raised: 22100,
    backers: 445,
    daysLeft: 7,
    location: "Barcelona, ES",
  },
  {
    id: "smart-water-bottle",
    title: "Hydra — Smart Water Bottle",
    tagline: "Stay hydrated. Track your intake.",
    description: "Insulated bottle with LED reminder and app. Tracks intake and syncs with fitness apps.",
    category: "Lifestyle",
    creator: "HydrateTech",
    image: "https://images.unsplash.com/photo-1602143407151-7111542de93e?w=800&q=80",
    goal: 22000,
    raised: 15600,
    backers: 289,
    daysLeft: 19,
    location: "Austin, US",
  },
  {
    id: "yoga-mat-pro",
    title: "GripFlow — Non-Slip Yoga Mat",
    tagline: "No more slipping. Extra thick, eco rubber.",
    description: "6mm natural rubber mat with alignment lines. Non-slip in sweat. Available in 5 colors.",
    category: "Lifestyle",
    creator: "Flow Studio",
    image: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&q=80",
    goal: 12000,
    raised: 18900,
    backers: 534,
    daysLeft: 3,
    location: "Bali, ID",
  },
  // More Community
  {
    id: "community-tool-library",
    title: "ToolShare — Neighborhood Tool Library",
    tagline: "Borrow tools. Share skills. Build together.",
    description: "Community tool library with 200+ tools. Membership includes workshops and repair café access.",
    category: "Community",
    creator: "ShareSpace",
    image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800&q=80",
    goal: 28000,
    raised: 14200,
    backers: 178,
    daysLeft: 38,
    location: "Ghent, BE",
  },
  {
    id: "urban-beehives",
    title: "CityBee — Urban Beehive Network",
    tagline: "Bees in the city. Honey for the neighborhood.",
    description: "Place beehives on rooftops and in parks. Local honey for backers; education for schools.",
    category: "Community",
    creator: "Urban Hive",
    image: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800&q=80",
    goal: 32000,
    raised: 28900,
    backers: 412,
    daysLeft: 11,
    location: "Copenhagen, DK",
  },
  {
    id: "free-fridge-network",
    title: "FridgeShare — Community Fridge Network",
    tagline: "Share food. Fight waste. Feed the neighborhood.",
    description: "Install 10 community fridges in food deserts. Anyone can give or take. Partnering with local grocers.",
    category: "Community",
    creator: "FoodShare NL",
    image: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=800&q=80",
    goal: 25000,
    raised: 11200,
    backers: 156,
    daysLeft: 45,
    location: "Amsterdam, NL",
  },
  // More Environment
  {
    id: "compost-bin-smart",
    title: "EcoBin — Smart Kitchen Composter",
    tagline: "Turn food scraps into soil. No smell, no mess.",
    description: "Countertop composter with charcoal filter and removable bin. Ready for garden or municipal collection.",
    category: "Environment",
    creator: "EcoHome",
    image: "https://images.unsplash.com/photo-1598902108850-9db8b9dc8a61?w=800&q=80",
    goal: 35000,
    raised: 42100,
    backers: 623,
    daysLeft: 8,
    location: "Dublin, IE",
  },
  {
    id: "reusable-straw-set",
    title: "StrawPack — Reusable Straw & Cutlery Set",
    tagline: "Stainless steel. Fits in your pocket.",
    description: "4 straws + fork, spoon, knife in a compact case. Dishwasher safe. Perfect for travel.",
    category: "Environment",
    creator: "ZeroPack",
    image: "https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?w=800&q=80",
    goal: 8000,
    raised: 15600,
    backers: 890,
    daysLeft: 2,
    location: "Berlin, DE",
  },
  {
    id: "solar-garden-lights",
    title: "SunPath — Solar Garden Lights",
    tagline: "Light your garden. Zero cables.",
    description: "Set of 12 solar path lights with warm LED. Auto on/off. Weather-resistant.",
    category: "Environment",
    creator: "GardenLight",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    goal: 18000,
    raised: 22100,
    backers: 445,
    daysLeft: 14,
    location: "Lisbon, PT",
  },
  // More Education
  {
    id: "language-flashcards",
    title: "WordFlow — Language Flashcards App",
    tagline: "Learn 10 words a day. Spaced repetition, native audio.",
    description: "App for 12 languages with native speaker audio and spaced repetition. Offline mode included.",
    category: "Education",
    creator: "Lingua Labs",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    goal: 25000,
    raised: 18900,
    backers: 534,
    daysLeft: 21,
    location: "Helsinki, FI",
  },
  {
    id: "science-kit-kids",
    title: "LabJunior — Science Kit for Kids 8+",
    tagline: "50 experiments. Real science. Real fun.",
    description: "Subscription or one-time kit with safe experiments. Chemistry, physics, biology. Parent guide included.",
    category: "Education",
    creator: "Science for All",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&q=80",
    goal: 30000,
    raised: 42100,
    backers: 678,
    daysLeft: 5,
    location: "Oxford, UK",
  },
  {
    id: "math-game-tablet",
    title: "NumBlast — Math Game for Ages 6–12",
    tagline: "Master math through play.",
    description: "Tablet game with adaptive difficulty. Covers arithmetic, fractions, and logic. Used in 50+ schools.",
    category: "Education",
    creator: "EduPlay",
    image: "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=800&q=80",
    goal: 40000,
    raised: 28900,
    backers: 412,
    daysLeft: 28,
    location: "Toronto, CA",
  },
  // More Art
  {
    id: "street-art-prints",
    title: "WallFlow — Street Art Print Collection",
    tagline: "Gallery-quality prints from 15 street artists.",
    description: "Limited edition prints from artists in Berlin, London, and NYC. Signed and numbered. A2 and A3.",
    category: "Art",
    creator: "Urban Canvas",
    image: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&q=80",
    goal: 20000,
    raised: 31200,
    backers: 445,
    daysLeft: 10,
    location: "Berlin, DE",
  },
  {
    id: "ceramic-mug-set",
    title: "Mud & Form — Handmade Ceramic Mugs",
    tagline: "Every mug is one of a kind.",
    description: "Set of 4 hand-thrown ceramic mugs. Food-safe glaze. Each piece unique.",
    category: "Art",
    creator: "Studio Mud",
    image: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=800&q=80",
    goal: 12000,
    raised: 18900,
    backers: 312,
    daysLeft: 16,
    location: "Delft, NL",
  },
  {
    id: "photography-zine",
    title: "Frame — Photography Zine Vol. 1",
    tagline: "Analog photography from 10 emerging artists.",
    description: "48-page zine. Film only. Limited run of 500. High-quality print.",
    category: "Art",
    creator: "Frame Collective",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80",
    goal: 8000,
    raised: 11200,
    backers: 234,
    daysLeft: 25,
    location: "Melbourne, AU",
  },
  // More Film & Video
  {
    id: "short-film-animation",
    title: "Dust — Animated Short Film",
    tagline: "A story of memory and loss. 15 minutes.",
    description: "Hand-drawn animation short. Festival run planned. Backers get early digital release and credits.",
    category: "Film & Video",
    creator: "Dust Studio",
    image: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800&q=80",
    goal: 45000,
    raised: 38200,
    backers: 892,
    daysLeft: 18,
    location: "Paris, FR",
  },
  {
    id: "doc-series-climate",
    title: "Turning Tide — Climate Doc Series",
    tagline: "6 episodes. Scientists and communities on the front line.",
    description: "Documentary series following climate researchers and affected communities. For streaming and educational use.",
    category: "Film & Video",
    creator: "Green Lens",
    image: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&q=80",
    goal: 95000,
    raised: 52100,
    backers: 1203,
    daysLeft: 32,
    location: "Reykjavik, IS",
  },
  {
    id: "indie-horror-film",
    title: "The Hollow — Indie Horror Feature",
    tagline: "Low-budget horror. High ambition.",
    description: "Feature-length indie horror. Already shot; funds for post-production and festival submission.",
    category: "Film & Video",
    creator: "Nightfall Pictures",
    image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800&q=80",
    goal: 35000,
    raised: 18900,
    backers: 356,
    daysLeft: 41,
    location: "Manchester, UK",
  },
  // More Music
  {
    id: "vinyl-record-album",
    title: "Echoes — Debut Album on Vinyl",
    tagline: "Dream pop from Oslo. 12\" gatefold.",
    description: "First vinyl pressing. 500 copies. Gatefold sleeve, 180g vinyl. Digital included.",
    category: "Music",
    creator: "Echoes Band",
    image: "https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=800&q=80",
    goal: 22000,
    raised: 28900,
    backers: 534,
    daysLeft: 6,
    location: "Oslo, NO",
  },
  {
    id: "acoustic-guitar",
    title: "FolkWood — Handmade Acoustic Guitar",
    tagline: "Small luthier. Big sound.",
    description: "Solid wood acoustic guitar. Spruce top, rosewood back. Built to order in 3 months.",
    category: "Music",
    creator: "FolkWood Guitars",
    image: "https://images.unsplash.com/photo-1525201548942-d8732f6617a0?w=800&q=80",
    goal: 55000,
    raised: 32100,
    backers: 89,
    daysLeft: 48,
    location: "Cremona, IT",
  },
  {
    id: "podcast-mic-bundle",
    title: "CastMic — Podcast Starter Bundle",
    tagline: "Pro sound. One cable.",
    description: "USB-C dynamic mic + arm + pop filter. Plug and play. No interface needed.",
    category: "Music",
    creator: "PodGear",
    image: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=800&q=80",
    goal: 18000,
    raised: 42100,
    backers: 890,
    daysLeft: 4,
    location: "Los Angeles, US",
  },
  // More Design
  {
    id: "desk-organizer",
    title: "TidyDesk — Bamboo Desk Organizer",
    tagline: "Keep cables and clutter at bay.",
    description: "Bamboo desk tray with cable holes and compartments. Fits monitor, keyboard, and accessories.",
    category: "Design",
    creator: "Tidy Co",
    image: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&q=80",
    goal: 12000,
    raised: 18900,
    backers: 445,
    daysLeft: 12,
    location: "Tokyo, JP",
  },
  {
    id: "backpack-minimal",
    title: "CarryOne — Minimal Daily Backpack",
    tagline: "15\" laptop. Rainproof. Lifetime warranty.",
    description: "Minimal backpack with laptop sleeve, hidden pocket, and recycled fabric. One size, three colors.",
    category: "Design",
    creator: "Carry Co",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
    goal: 35000,
    raised: 52100,
    backers: 678,
    daysLeft: 9,
    location: "Zurich, CH",
  },
  {
    id: "lamp-desk-led",
    title: "Glow — LED Desk Lamp",
    tagline: "Adjustable brightness and color temperature.",
    description: "Sleek LED desk lamp with touch dimmer and 3 color temps. USB port for charging.",
    category: "Design",
    creator: "LightForm",
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80",
    goal: 25000,
    raised: 18200,
    backers: 312,
    daysLeft: 26,
    location: "Seoul, KR",
  },
  // More Publishing
  {
    id: "cookbook-vegan",
    title: "Plant — Vegan Cookbook",
    tagline: "80 recipes. No compromise on taste.",
    description: "Hardcover cookbook with 80 plant-based recipes. Beautiful photography. From a chef and nutritionist.",
    category: "Publishing",
    creator: "Plant Press",
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&q=80",
    goal: 28000,
    raised: 35200,
    backers: 890,
    daysLeft: 2,
    location: "London, UK",
  },
  {
    id: "comic-book-digital",
    title: "Neon Drift — Digital Comic Series",
    tagline: "Sci-fi noir. 6 issues.",
    description: "Digital comic series. 6 issues, 24 pages each. PDF and CBZ. Print run as stretch goal.",
    category: "Publishing",
    creator: "Neon Comics",
    image: "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=800&q=80",
    goal: 15000,
    raised: 12400,
    backers: 356,
    daysLeft: 33,
    location: "Brooklyn, US",
  },
  {
    id: "magazine-indie",
    title: "Drift — Indie Travel Magazine",
    tagline: "Slow travel. Issue 1.",
    description: "Print magazine. 100 pages. Stories from slow travelers. Sustainable and thoughtful.",
    category: "Publishing",
    creator: "Drift Media",
    image: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=800&q=80",
    goal: 18000,
    raised: 22100,
    backers: 445,
    daysLeft: 17,
    location: "Lisbon, PT",
  },
  // More Games
  {
    id: "puzzle-game-mobile",
    title: "FlowState — Puzzle Game for Mobile",
    tagline: "Relaxing puzzles. No ads, no timers.",
    description: "Mobile puzzle game with 100+ levels. Calm aesthetics. One-time purchase, no IAP.",
    category: "Games",
    creator: "Puzzle Lab",
    image: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=800&q=80",
    goal: 20000,
    raised: 28900,
    backers: 623,
    daysLeft: 20,
    location: "Helsinki, FI",
  },
  {
    id: "dice-set-premium",
    title: "RollForge — Premium Dice Set",
    tagline: "Metal and resin dice for tabletop gamers.",
    description: "Set of 7 metal or resin dice. Multiple colorways. Comes in a wooden box.",
    category: "Games",
    creator: "DiceCraft",
    image: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800&q=80",
    goal: 10000,
    raised: 35600,
    backers: 890,
    daysLeft: 1,
    location: "Dresden, DE",
  },
  // Extra to reach 6+ per category: Games +1, others +2
  {
    id: "coop-video-game",
    title: "Haven — Co-op Adventure Game",
    tagline: "Play together. Explore a lost planet.",
    description: "2-player co-op game. Explore, craft, and survive on a mysterious planet. PC and consoles.",
    category: "Games",
    creator: "Duo Games",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80",
    goal: 65000,
    raised: 28900,
    backers: 445,
    daysLeft: 27,
    location: "Montreal, CA",
  },
  {
    id: "sleep-tracker-band",
    title: "RestBand — Sleep Tracker",
    tagline: "Better sleep. Smarter recovery.",
    description: "Wearable that tracks sleep stages and gives morning insights. No subscription required.",
    category: "Lifestyle",
    creator: "Rest Labs",
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&q=80",
    goal: 28000,
    raised: 15600,
    backers: 312,
    daysLeft: 23,
    location: "San Francisco, US",
  },
  {
    id: "tea-set-organic",
    title: "Leaf & Stem — Organic Tea Set",
    tagline: "Loose-leaf tea. Ceramic pot and infuser.",
    description: "Ceramic teapot with stainless infuser. Set of 3 organic tea blends. Gift box.",
    category: "Lifestyle",
    creator: "Tea Craft",
    image: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=800&q=80",
    goal: 12000,
    raised: 18900,
    backers: 423,
    daysLeft: 8,
    location: "Kyoto, JP",
  },
  {
    id: "repair-cafe-kit",
    title: "FixKit — Repair Café Starter Kit",
    tagline: "Everything to run a community repair café.",
    description: "Tool set, signage, and guide for starting a repair café. Reduce waste, share skills.",
    category: "Community",
    creator: "Repair Together",
    image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800&q=80",
    goal: 15000,
    raised: 11200,
    backers: 178,
    daysLeft: 40,
    location: "Leuven, BE",
  },
  {
    id: "local-food-map",
    title: "FarmMap — Local Food Map App",
    tagline: "Find farms, markets, and pick-your-own near you.",
    description: "App and map for local food. Direct from farmer. Available in 5 countries at launch.",
    category: "Community",
    creator: "Local Bite",
    image: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800&q=80",
    goal: 22000,
    raised: 18900,
    backers: 356,
    daysLeft: 16,
    location: "Bristol, UK",
  },
  {
    id: "bamboo-cutlery",
    title: "BambooGo — Bamboo Cutlery Set",
    tagline: "Travel cutlery. Light and durable.",
    description: "Bamboo fork, spoon, knife, and straw in a compact case. For picnics and travel.",
    category: "Environment",
    creator: "EcoPack",
    image: "https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?w=800&q=80",
    goal: 8000,
    raised: 22100,
    backers: 534,
    daysLeft: 4,
    location: "Barcelona, ES",
  },
  {
    id: "water-filter-bottle",
    title: "PureFlow — Filter Water Bottle",
    tagline: "Clean water anywhere. Replaceable filter.",
    description: "Bottle with built-in filter. Removes bacteria and microplastics. Filter lasts 2 months.",
    category: "Environment",
    creator: "PureTech",
    image: "https://images.unsplash.com/photo-1602143407151-7111542de93e?w=800&q=80",
    goal: 35000,
    raised: 28900,
    backers: 445,
    daysLeft: 19,
    location: "Zurich, CH",
  },
  {
    id: "history-podcast-kids",
    title: "TimeTales — History Podcast for Kids",
    tagline: "Stories from the past. For curious minds 7+.",
    description: "Weekly podcast. One historical figure or event per episode. Fun and accurate.",
    category: "Education",
    creator: "EduSound",
    image: "https://images.unsplash.com/photo-1589903308904-1010c2294adc?w=800&q=80",
    goal: 18000,
    raised: 12400,
    backers: 289,
    daysLeft: 31,
    location: "Boston, US",
  },
  {
    id: "chess-set-kids",
    title: "CheckMate — Chess Set for Kids",
    tagline: "Learn chess. Magnetic, travel-friendly.",
    description: "Magnetic chess set with illustrated guide. Pieces store in the board. Ages 5+.",
    category: "Education",
    creator: "BrainPlay",
    image: "https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=800&q=80",
    goal: 12000,
    raised: 18900,
    backers: 412,
    daysLeft: 11,
    location: "Prague, CZ",
  },
  {
    id: "sculpture-mini",
    title: "Tiny Worlds — Miniature Sculptures",
    tagline: "Hand-painted mini sculptures. Collectible.",
    description: "Set of 5 miniature sculptures. Resin, hand-painted. Display stand included.",
    category: "Art",
    creator: "Mini Art Co",
    image: "https://images.unsplash.com/photo-1561214115-f2f134e49ac4?w=800&q=80",
    goal: 15000,
    raised: 22100,
    backers: 445,
    daysLeft: 6,
    location: "Tokyo, JP",
  },
  {
    id: "linocut-prints",
    title: "Press & Ink — Linocut Print Set",
    tagline: "Original linocut prints. Signed and numbered.",
    description: "Set of 4 linocut prints. Nature theme. Limited edition of 100. A4 size.",
    category: "Art",
    creator: "Press Studio",
    image: "https://images.unsplash.com/photo-1515405295579-ba7b45403062?w=800&q=80",
    goal: 10000,
    raised: 15600,
    backers: 312,
    daysLeft: 22,
    location: "Leeds, UK",
  },
  {
    id: "short-doc-music",
    title: "Sound Roots — Music Documentary",
    tagline: "Where does our music come from? 45 min.",
    description: "Documentary about traditional instruments and their modern use. Festival screenings.",
    category: "Film & Video",
    creator: "Sound Vision",
    image: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&q=80",
    goal: 38000,
    raised: 21200,
    backers: 445,
    daysLeft: 24,
    location: "Nashville, US",
  },
  {
    id: "web-series-comedy",
    title: "FlatShare — Comedy Web Series",
    tagline: "6 episodes. Life in a shared flat.",
    description: "Comedy web series. 6 x 12 min. Already shot; funds for post and release.",
    category: "Film & Video",
    creator: "Flat Productions",
    image: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800&q=80",
    goal: 22000,
    raised: 18900,
    backers: 356,
    daysLeft: 18,
    location: "Cologne, DE",
  },
  {
    id: "pedal-effects",
    title: "ToneBox — Guitar Effects Pedal",
    tagline: "Analog overdrive. Hand-wired.",
    description: "Boutique overdrive pedal. Hand-wired in the UK. Limited run of 200.",
    category: "Music",
    creator: "Tone Craft",
    image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&q=80",
    goal: 18000,
    raised: 24500,
    backers: 312,
    daysLeft: 3,
    location: "Sheffield, UK",
  },
  {
    id: "headphones-kids",
    title: "SafeSound — Kids Headphones",
    tagline: "Volume-limited. Safe for little ears.",
    description: "Volume capped at 85dB. Durable, adjustable. For ages 3–10. Three colors.",
    category: "Music",
    creator: "SafeGear",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80",
    goal: 25000,
    raised: 18200,
    backers: 423,
    daysLeft: 29,
    location: "Amsterdam, NL",
  },
  {
    id: "notebook-set",
    title: "GridBook — Dot-Grid Notebook Set",
    tagline: "3 notebooks. 200 pages. Sustainable paper.",
    description: "Set of 3 A5 dot-grid notebooks. Recycled paper. Lay-flat binding. For notes and sketches.",
    category: "Design",
    creator: "Grid Co",
    image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&q=80",
    goal: 8000,
    raised: 22100,
    backers: 534,
    daysLeft: 2,
    location: "Stockholm, SE",
  },
  {
    id: "pen-ergonomic",
    title: "WriteFlow — Ergonomic Pen",
    tagline: "Designed for long writing. No cramp.",
    description: "Ergonomic pen with grip. Refillable. For students and writers. Multiple colors.",
    category: "Design",
    creator: "Write Co",
    image: "https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=800&q=80",
    goal: 15000,
    raised: 12400,
    backers: 289,
    daysLeft: 35,
    location: "Seoul, KR",
  },
  {
    id: "poetry-collection",
    title: "Quiet Hours — Poetry Collection",
    tagline: "First collection. 60 poems.",
    description: "Debut poetry collection. Hardcover. 60 poems. From an award-winning poet.",
    category: "Publishing",
    creator: "Quiet Press",
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&q=80",
    goal: 12000,
    raised: 18900,
    backers: 445,
    daysLeft: 13,
    location: "Dublin, IE",
  },
  {
    id: "recipe-zine",
    title: "Seasonal — Recipe Zine Quarterly",
    tagline: "4 issues. Seasonal, local recipes.",
    description: "Quarterly recipe zine. 24 pages. Vegetarian focus. Beautiful photography.",
    category: "Publishing",
    creator: "Seasonal Press",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    goal: 10000,
    raised: 11200,
    backers: 234,
    daysLeft: 26,
    location: "Copenhagen, DK",
  },
];

export function getStartupById(id: string): Startup | undefined {
  return startups.find((s) => s.id === id);
}

export function getFeaturedStartups(): Startup[] {
  return startups.filter((s) => s.featured);
}

export function getStartupsByCategory(category: string): Startup[] {
  return startups.filter((s) => s.category === category);
}

export const categoryOrder = [
  "Tech & Gadgets",
  "Games",
  "Lifestyle",
  "Community",
  "Environment",
  "Education",
  "Art",
  "Film & Video",
  "Music",
  "Design",
  "Publishing",
];
